select * from customer limit 10
-- Questions to be answered
-- Q1. what is the total revenue generated by male vs female customers?
-- a standard biz question, it compares revenues across demographics
select gender, sum(purchase_amount) as revenue
from customer
group by gender

--Q2. which customers used a discount but still spent more than the average purchase amount
select customer_id,discount_applied
from customer
where discount_applied='Yes' AND purchase_amount>=(select  AVG (purchase_amount) from customer)

--Q3. which are the top 5 products with the highest  average vreview rating 
select item_purchased,round(avg(review_rating::numeric),2) as avg_max_rating 
from customer
group by item_purchased
order by avg_max_rating desc
limit 5

--Q4.compare the average purchase amount between the standard and express shipping

select shipping_type,round(avg(purchase_amount),2) as average_purchase
from customer 
where shipping_type IN ('Standard','Express') 
group by shipping_type

--Q5. Do subscribed customers spend more? compare average spend and total revenue 
-- between subscribers and non-subscribers
select
	subscription_status, 
	count(customer_id) as total_customers,
	round(avg(purchase_amount),2) as avg_purchase_amount,
	round(sum(purchase_amount),2)as total_revenue
from 
	customer
group by 
	subscription_status
order by
	total_revenue,avg_purchase_amount

--Q6. which 5 products have the highest percentage of purchases with discount supplied

select
	item_purchased,
	round(100*SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/count(*),2)as discount_rate
from
	customer
group by 
	item_purchased
order by 
	discount_rate desc
limit 5;

-- Q7. Segment customers into new, returning and loyal based on their total number
-- of previous purchased and show the count of each segment

with customer_type as (
select customer_id,previous_purchases,
CASE
	WHEN previous_purchases=1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END as customer_segment
From
	customer
)
select customer_segment, count(distinct customer_id) as number_of_customers
from customer_type
group by customer_segment;

--Q8. what are the top three most purchased products within each category

with item_counts as(
SELECT
	item_purchased,
	category,
	COUNT(customer_id)as total_orders,
	ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
	from customer
	group by category, item_purchased
)

select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3;

-- Q9. Are customers who ae repeat buyers (more than 5 purchases) also likely to subscribe

select subscription_status, count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group

select age_group, sum(purchase_amount) as revenue
from customer
group by age_group 
order by revenue desc












